version: "2"
services:
  blog:
    build: ./docker/php
    volumes:
      - ./blog:/app
    working_dir: /app
    links:
      - hypernova
    ports:
      - 8000:8000
  hypernova:
    image: node:10-slim
    volumes:
      - ./hypernova:/app
    working_dir: /app
    ports:
      - 3000:3000
    command:
      - yarn
      - dev
    environment:
      PORT: 3000 
  proxy:
    build: ./proxy
    links:
      - blog
      - hypernova
    ports:
      - 8080:8080
    environment:
      HYPERNOVA_BATCH: 'http://hypernova:3000/batch'
  